src/pug/pages/index.pug

masterにプロテクトかかってて直接いじれないので出します。

index.pugの追加

---

.gitignore
src/pug/pages/index.pug
src/scss/layouts/_container.scss

#3 
layouts/_container.sassにてコンテナ設計を行いました。

container 設計 #3

---

gulpfile.js

gulpfileの修正 #14

---

src/pug/layouts/_base.pug
src/pug/lib/_heading.pug
src/scss/components/_heading.scss

#1
heading.pugを作成し、heading.scssを設定しました。
```+heading('FEATURE', "特徴")```というように引数でそれぞれの見出しの文字を渡して使えるようになっているはずです。
ただ全体で使われているfontと#707070の部分はここでは設定してないです。

見出しコンポーネント設計 #1

---

src/scss/lib/_common.scss

ウェブフォントの修正 #10

---

src/pug/layouts/_base.pug
src/pug/layouts/_footer.pug
src/pug/lib/_footer-content.pug
src/scss/layouts/_footer.scss
src/scss/lib/_common.scss

#25 
フッターの作成を行いました。ソーシャルアイコンはFont Awesomesを用いました。

フッター実装 #25

---

src/pug/_config.pug
src/pug/pages/index.pug

タイトル設定 #42

---

src/pug/layouts/_base.pug
src/pug/pages/index.pug

#54 
_base.pugで読み込まれていたlibの内容を、footerの分を除いてindex.pugに移動しました。

base.pugの修正 #54

---

src/pug/pages/index.pug
src/scss/layouts/_carousel.scss
src/scss/layouts/_feature.scss

#59 
- index.pugにおける/lib/*と/layouts/*の読み込み順を変更
- _carousel.scssの軽微な修正

index.pugの修正#59

---

src/pug/layouts/_base.pug
src/pug/layouts/_feature.pug
src/pug/layouts/_header.pug
src/scss/components/_card.scss
src/scss/components/_hero.scss
src/scss/layouts/_carousel.scss

パス指定の修正 #62

---

src/pug/layouts/_media.pug
src/pug/lib/_heading.pug
src/pug/lib/_popular-card.pug

#60 
HTML Validatorを通るように修正しました。
- heading.pugのheading.headingを.headingに変更。
- popular-card.pugの.card__nameにh2タグを付与。
- それに伴いMEDIAセクションのh3タグをh2タグに変更。
- media.pugの埋め込みタグ中のframeborderを削除、style属性を付与。

validetorチェックを通るよう修正 #60

---

src/pug/lib/_popular-card.pug

#63 
残っていた_popular-card.pugの文法エラーを修正しました。再度マージお願いします。

_popular-card.pugの文法エラー修正 #63

---

src/scss/layouts/_carousel.scss

#71 
- グラデーション の色を白から黒に変更
- 実機確認済み

グラデーションの修正 #71

---

src/scss/components/_section.scss

#81 
https://github.com/Update-hub/stage-2-antyoku/blob/75f1a0fd1df42682ee8dc3ae8f23ffbb89e5a07c/src/scss/components/_section.scss#L14
上記のファイルから`.section--limited`を削除しました。

section scss見直し#81

---

src/pug/layouts/_base.pug
src/scss/style.scss

#82 
style.cssのインポートファイルのurlを統一しました
https://github.com/Update-hub/stage-2-antyoku/pull/91/files#diff-b86aa89eb58031c905f46ced082fdd9f

styleのurl統一#82

---

src/pug/lib/_footer-content.pug
src/scss/layouts/_footer.scss

#76 
フッターの各項目にaタグを付与し、スタイルを整えました。

フッターコンポーネント #76

---

src/pug/lib/_heading.pug
src/scss/components/_heading.scss

#75 
headingのリファクタを行いました。
- ボーダーの疑似要素化
- headingをtable要素に変更し、wrapを削除

headingの修正 #75

---

src/pug/layouts/_base.pug

#100 
- jqueryが正しく読み込まれるよう修正しました。

url表記の修正 #100

---

src/pug/lib/_popular-card.pug

#104 
#95 のコンフリクト解消時に誤って削除したと思われます。お手数おかけして申し訳ありませんがよろしくお願いします。

テキストの修復 #104

---

src/pug/lib/_carousel-content.pug
src/scss/components/_carousel.scss

#74 
(#Issue番号 を記述してください)
カルセール内のカートに追加テキストをリンクに変更
(作業概要をわかりやすく記述してください)

fix/74:カートに追加テキストをリンクに変更#74

---

src/pug/lib/_heading.pug
src/scss/components/_card.scss
src/scss/components/_heading.scss
src/scss/layouts/_container.scss

#107 
- 下線をボーダーではなくブロック要素にしました。
- popularセクションのcontainerに不必要なマージンが設定されていたので削除しました。

heading設計の見直し #107

---

src/js/favorite-btn.js
src/pug/lib/_popular-card.pug
src/scss/components/_button.scss
src/scss/components/_card.scss

#110 #112 
- クリックできる部分でカーソルがポインターに変化するようにしました。
- ハート部分をtoggleにし、transitionを追加しました。

カード設計の調整 #110 #112
